name: Build AppImage

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: sudo chmod +x get-dependencies.sh && sudo ./get-dependencies.sh

      - name: Build AppImage
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: chmod +x make-appimage.sh && ./make-appimage.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Karere-AppImage
          path: "*.AppImage"
